#pragma config(Sensor, in1,    IRsensor1,      sensorReflection)
#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  button2,        sensorTouch)
#pragma config(Sensor, dgtl3,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl9,  TFar,           sensorDigitalOut)
#pragma config(Sensor, dgtl12, TClose,         sensorDigitalOut)
#pragma config(Motor,  port1,           LEFT,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          RIGHT,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	SensorValue[TFar] = 0;
	SensorValue[TClose] = 0;
	// When tfar and tclose are both on the distance is good for the mechanism
	while(true){
		while(SensorValue[sonar] > 35 || SensorValue[sonar] <= 0) {
			SensorValue[TFar] = 1;
			SensorValue[TClose] = 0;
		} // While robot is greater than 35cm away, TFar is on as it is too far for mechanism
		while((SensorValue[sonar] > 15 && SensorValue[sonar] < 35) || SensorValue[sonar] <= 0) {
			SensorValue[TClose] = 1;
		} // Both LED's are on when robot is 35cm away and is close enough for mechanism
		while(SensorValue[sonar] < 15 || SensorValue[sonar] <= 0) {
			SensorValue[TClose] = 1;
			SensorValue[TFar] = 0;
		} // When closer than 15cm TFar turns off and TClose stays on
}
}
